/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as tabsRouteRouteImport } from './routes/(tabs)/route'
import { Route as tabsIndexRouteImport } from './routes/(tabs)/index'
import { Route as tabsHistoryRouteImport } from './routes/(tabs)/history'

const tabsRouteRoute = tabsRouteRouteImport.update({
  id: '/(tabs)',
  getParentRoute: () => rootRouteImport,
} as any)
const tabsIndexRoute = tabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => tabsRouteRoute,
} as any)
const tabsHistoryRoute = tabsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => tabsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/history': typeof tabsHistoryRoute
  '/': typeof tabsIndexRoute
}
export interface FileRoutesByTo {
  '/history': typeof tabsHistoryRoute
  '/': typeof tabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(tabs)': typeof tabsRouteRouteWithChildren
  '/(tabs)/history': typeof tabsHistoryRoute
  '/(tabs)/': typeof tabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/history' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/history' | '/'
  id: '__root__' | '/(tabs)' | '/(tabs)/history' | '/(tabs)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  tabsRouteRoute: typeof tabsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(tabs)': {
      id: '/(tabs)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof tabsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tabs)/': {
      id: '/(tabs)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof tabsIndexRouteImport
      parentRoute: typeof tabsRouteRoute
    }
    '/(tabs)/history': {
      id: '/(tabs)/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof tabsHistoryRouteImport
      parentRoute: typeof tabsRouteRoute
    }
  }
}

interface tabsRouteRouteChildren {
  tabsHistoryRoute: typeof tabsHistoryRoute
  tabsIndexRoute: typeof tabsIndexRoute
}

const tabsRouteRouteChildren: tabsRouteRouteChildren = {
  tabsHistoryRoute: tabsHistoryRoute,
  tabsIndexRoute: tabsIndexRoute,
}

const tabsRouteRouteWithChildren = tabsRouteRoute._addFileChildren(
  tabsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  tabsRouteRoute: tabsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
